Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: dev.vedikasharma.birdingexcursion.GetItineraryLambda
      CodeUri: /Users/vedikasharma/eclipse-workspace/FeatherQuest/birdingexcursion
      Runtime: java21
      Architectures:
        - x86_64